; PlatformIO Project Configuration File
;
; Simple single environment for building/uploading the module.
; This uses the standard env name `teensy40` like before.

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
monitor_port =